### ISSUE TITLE
Dont run on ubuntu 20

### ISSUE THREAD

**Issue by enrutador** [jphilll/AsusRouterMonitor#1]
Hi
Very nice work. Debian 9 is too old, i prove on ubuntu 20 and doesn t work , with python 3.9 or 3.8:

#python3.8 asusMonitor.py
Traceback (most recent call last):
  File "asusMonitor.py", line 47, in <module>
    logging.basicConfig(filename='/var/log/asusMonitor.log', encoding='utf-8', format='%(asctime)s - %(levelname)s - %(message)s', level=logging.WARNING)
  File "/usr/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

All the requirements are install:

# pip install -r ./requirements.txt
Requirement already satisfied: requests in /usr/local/src/requests (from -r ./requirements.txt (line 1)) (2.26.0)
Requirement already satisfied: regex in /usr/local/lib/python3.8/dist-packages (from -r ./requirements.txt (line 2)) (2021.11.10)
Requirement already satisfied: apscheduler in /usr/local/lib/python3.8/dist-packages (from -r ./requirements.txt (line 3)) (3.8.1)
Requirement already satisfied: mysql-connector-python-rf in /usr/local/lib/python3.8/dist-packages (from -r ./requirements.txt (line 4)) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r ./requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r ./requirements.txt (line 1)) (1.25.8)
Requirement already satisfied: charset_normalizer~=2.0.0 in /usr/local/lib/python3.8/dist-packages (from requests->-r ./requirements.txt (line 1)) (2.0.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r ./requirements.txt (line 1)) (2.8)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from apscheduler->-r ./requirements.txt (line 3)) (45.2.0)
Requirement already satisfied: pytz in /usr/lib/python3/dist-packages (from apscheduler->-r ./requirements.txt (line 3)) (2019.3)
Requirement already satisfied: tzlocal!=3.*,>=2.0 in /usr/lib/python3/dist-packages (from apscheduler->-r ./requirements.txt (line 3)) (2.1b1)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from apscheduler->-r ./requirements.txt (line 3)) (1.14.0)

Can you help me to test on ubuntu 20?

**Comment by jphilll** [comment]
Hi, thank you for using my work!
After some searching on Google, I ~think~ realized the `encoding` option in `logging.basicConfig( )` was only added in Python 3.9.
Sorry for the inconvenience, I will make change to the `README`.

**Comment by enrutador** [comment]
Thanks ¡¡¡¡ with 3.9 installed  run without problems ¡¡¡
Good work
