### ISSUE TITLE
Got an error with encoding

### ISSUE THREAD

**Issue by el97** [jphilll/AsusRouterMonitor#3]
It looks like I have an error with encoding. This is what I get when I run the command `python3 asusMonitor.py`. I'm kind of new to python and programming overall so It would be really nice to get some help with this. I'm also trying to host the monitor on a Raspberry Pi 4 if that makes a difference.

```
Traceback (most recent call last):
  File "AsusMonitor.py", line 46, in <module>
    logging.basicConfig(filename='/var/log/asusMonitor.log', encoding='utf8', format='%(asctime)s - %(levelname)s - %(message)s', level=logging.WARNING)
  File "/usr/lib/python3.7/logging/__init__.py", line 1921, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding
```

**Comment by jphilll** [comment]
Try Python 3.9

**Comment by el97** [comment]
It looks like that worked for the encoding issue. But it looks like it lead me to another one. 
```
Traceback (most recent call last):
  File "/home/pi/GrafanaAsusRouterMonitor/asusMonitor.py", line 274, in <module>
    getAuth()
  File "/home/pi/GrafanaAsusRouterMonitor/asusMonitor.py", line 90, in getAuth
    token = sessions.cookies.get_dict()['asus_token']
KeyError: 'asus_token'
```

**Comment by jphilll** [comment]
What’s your router admin panel version?

**Comment by el97** [comment]
I guess that you mean the firmware version? I'm not sure how to find the specific panel version but the firmware I'm using is 3.0.0.4.386_45987 on a RT-AC88U.

**Comment by jphilll** [comment]
Are u using stock firmware from Asus or modified version like Merlin?

**Comment by jphilll** [comment]
This script may be too old, I haven’t used it for about a year now. Firmware may have been updated and something may be changed. I am using a RT-AC1900P so I cannot test your router model or firmware version. I am afraid that you have to adapt the script to your specific firmware. The logic is pretty simple if you have some experience of web and python. The key `asus_token` is extracted from the cookie when logging in to the panel, maybe the firmware doesn’t do this anymore, so you have to look for the correct token.

**Comment by el97** [comment]
> Are u using stock firmware from Asus or modified version like Merlin?

I am currently using the stock firmware from Asus.

> This script may be too old, I haven’t used it for about a year now. Firmware may have been updated and something may be changed. I am using a RT-AC1900P so I cannot test your router model or firmware version. I am afraid that you have to adapt the script to your specific firmware. The logic is pretty simple if you have some experience of web and python. The key `asus_token` is extracted from the cookie when logging in to the panel, maybe the firmware doesn’t do this anymore, so you have to look for the correct token. 

I see... The token should be visible if I use the debug function on my browser. I guess that we can close this issue due to the incompatibly.

**Comment by jphilll** [comment]
Yes, you can find it in debug mode, but it has a timeout time and will change. Anyways, good luck!

**Comment by el97** [comment]
It looks like it was because I used https with a specific port. If I use http://192.168.1.1 I manage to get the authentication to work.
